name: CI of project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest # ✅ fixed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMG=${{ secrets.DOCKER_USERNAME }}/renting-app
          docker build -t $IMG:latest .
          docker push $IMG:latest
